name: Docker Image CI

on:
  push:
    branches: [ "wasm-main" ]
  pull_request:
    branches: [ "wasm-main" ]

jobs:

  build:

    runs-on: rnd201

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag innoextract-wasm:$(date +%s)
