name: robot-tests-with-tags
run-name: robot-tests-with-tags:${{ inputs.testTag }}
on:
  workflow_dispatch:
    inputs:
      testTag:
        description: 'Test tags'
        required: true
        default: 'smoke'
        type: choice
        options:
        - Smoke
        - Daily
        - multiple
        - performance
        - poma
        - mrpo

jobs:

  build:

    runs-on: rnd201

    steps:
    - uses: actions/checkout@v3
    - name: Remove old logs from robot /output folder
      if: always()
      run: if [ -e /home/runner/build/output/log.html ]; then rm -r /home/runner/build/output/* ; else echo "File not found." ; fi
      
    - name: Start robot tests with tag
      run: xvfb-run -n 56 -e /dev/stdout -s '-screen 0 1366x768x24' -f /home/runner/.Xauthority sh -c 'startlxde& /home/runner/innoextract-wasm/tests/scripts/run_tag.sh ${{ inputs.testTag }}'
      
    - name: Run post test scripts
      if: always()
      run: /home/runner/innoextract-wasm/tests/scripts/run_post_test.sh $GITHUB_WORKFLOW ${{github.run_number}}
