name: robot-tests-copy
on:
  workflow_dispatch:
    inputs:
      testTag:
        description: 'Test tags'
        required: true
        default: 'smoke'
        type: choice
        options:
        - smoke
        - something else
        - 3rd choice

jobs:

  build:

    runs-on: rnd201

    steps:
    - name: Hash config
      run:  /home/runner/test.sh "${{ inputs.testTag }}"
