name: mytries
on:
  workflow_run:
    workflows: ["Docker Image CI"]
    branches: [wasm-main]
    types: 
      - completed

jobs:

  build:

    runs-on: rnd201

    steps:
    - name: touch simple file
      run: sudo touch /home/poma/ddd
